SELECT * WHERE{
    SERVICE <http://localhost:3050/test_dataset/sparql>{
        SELECT ?s {
            ?s ?p ?o
        }LIMIT 1024
    }
    SERVICE <https://id.ndl.go.jp/auth/ndla/sparql> {
        ?s ?p ?o
    }
}
